video:
  - id: 0
    description: "car"
    resolution: "1080p"
    fps: 25
    url: "rtsp://192.168.1.4/video0"
    pipeline:
      - service_name: "car_detection"
        service_port: 9001
  - id: 1
    description: "car"
    resolution: "1080p"
    fps: 30
    url: "rtsp://192.168.1.4/video1"
    pipeline:
      - service_name: "car_detection"
        service_port: 9001
  - id: 2
    description: "car"
    resolution: "1080p"
    fps: 30
    url: "rtsp://192.168.1.4/video2"
    pipeline:
      - service_name: "car_detection"
        service_port: 9001
