video:
  - id: 0
    description: "classroom"
    resolution: "1080p"
    fps: 30
    url: "rtsp://192.168.1.4/video0"
    pipeline:
      - service_name: "face_detection"
      - service_name: "pose_estimation"
  - id: 1
    description: "classroom"
    resolution: "1080p"
    fps: 30
    url: "rtsp://192.168.1.4/video1"
    pipeline:
      - service_name: "face_detection"
      - service_name: "pose_estimation"

